[input]
keys = ["Q", "W", "E", "R", "U", "I", "O", "P"]

[input.remap]
V = "LEFTSHIFT"

[output]
keys = ["A", "S", "E", "T", "N", "I", "O", "P"]

[output.chords]
AS = "W"
AE = "X"
AT = "F"
AN = "Q"
AI = "Z"
AO = "LEFTBRACE"
AP = "QUESTION"
SE = "D"
ST = "C"
SN = "J"
SI = "K"
SO = "DOT"
SP = ")"
ET = "R"
EN = "Y"
EI = "COMMA"
EO = "MINUS"
EP = "APOSTROPHE"
TN = "B"
TI = "V"
TO = "G"
TP = "BACKSPACE"
NI = "H"
NO = "U"
NP = "M"
IO = "L"
IP = "!"
OP = "SEMICOLON"
NIOP = "ENTER"
ASET = "TAB"
# exits asetniop
ASOP = "EXIT"
